//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intcom.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACESSO
    {
        private string _SENHA;

        public int ID_LOGIN { get; set; }
        public string USERNAME
        {
            get
            {
                return Safe.DecryptString(_SENHA);
            }
            set
            {
                _SENHA = Safe.EncryptString(value);
            }
        }
        public string SENHA { get; set; }
        public string ATIVO { get; set; }
        public string PERFIL { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
    }
}
